library(BSgenome)
library(MutationalPatterns)
library(NMF)
library("gridExtra")
file_path <- "/home/b06901011/mskcc-vcf2maf-bbe39fe/VCFMAF/sample_data/out_20201013/ms_input.tsv"
data <- read.table(file_path, header = TRUE, stringsAsFactors = FALSE)
data <- data+0.0001
nmf_res <- extract_signatures(data, rank = 4, nrun = 10)
colnames(nmf_res$signatures) <- c("Signature_0","Signature_1","Signature_2","Signature_3")
rownames(nmf_res$contribution) <- c("Signature_0","Signature_1","Signature_2","Signature_3")
png(filename="/home/b06901011/mskcc-vcf2maf-bbe39fe/VCFMAF/sample_data/pic/2_Signature_96.png",width = 1000, height = 1000)
plot_96_profile(nmf_res$signatures, condensed = TRUE)
dev.off()
pc1 <- plot_contribution(nmf_res$contribution, nmf_res$signature,mode = "relative")
pc2 <- plot_contribution(nmf_res$contribution, nmf_res$signature,mode = "absolute")
png(filename="/home/b06901011/mskcc-vcf2maf-bbe39fe/VCFMAF/sample_data/pic/3_Signature_Distribution.png",width = 1000, height = 1000)
a <- grid.arrange(pc1, pc2)
plot(a)
dev.off()
png(filename="/home/b06901011/mskcc-vcf2maf-bbe39fe/VCFMAF/sample_data/pic/4_Signature2sample_Heatmap.png",width = 1000, height = 1000)
pch1 <- plot_contribution_heatmap(nmf_res$contribution,sig_order = c("Signature_0","Signature_1","Signature_2","Signature_3"))
pch2 <- plot_contribution_heatmap(nmf_res$contribution, cluster_samples=FALSE)
grid.arrange(pch1, pch2, ncol = 2, widths = c(2,1.6))
dev.off()
png(filename="/home/b06901011/mskcc-vcf2maf-bbe39fe/VCFMAF/sample_data/pic/5_Similarity_Comparison.png",width = 1000, height = 1000)
plot_compare_profiles(data[,1],nmf_res$reconstructed[,1],profile_names = c("Original", "Reconstructed"),condensed = TRUE)
dev.off()
sp_url <- paste("https://cancer.sanger.ac.uk/cancergenome/assets/","signatures_probabilities.txt", sep = "")
cancer_signatures = read.table(sp_url, sep = "	", header = TRUE)
new_order = match(row.names(data), cancer_signatures$Somatic.Mutation.Type)
cancer_signatures = cancer_signatures[as.vector(new_order),]
row.names(cancer_signatures) = cancer_signatures$Somatic.Mutation.Type
cancer_signatures = as.matrix(cancer_signatures[,4:33])
hclust_cosmic = cluster_signatures(cancer_signatures, method = "average")
cosmic_order = colnames(cancer_signatures)[hclust_cosmic$order]
cos_sim_samples_signatures = cos_sim_matrix(nmf_res$signature, cancer_signatures)
png(filename="/home/b06901011/mskcc-vcf2maf-bbe39fe/VCFMAF/sample_data/pic/6_Signature_Similarity_heatmap.png",width = 800, height = 600)
plot_cosine_heatmap(cos_sim_samples_signatures,col_order = cosmic_order,cluster_rows = TRUE)
dev.off()
write.csv(nmf_res$contribution,file="/home/b06901011/mskcc-vcf2maf-bbe39fe/VCFMAF/sample_data/pic/nmf_res_contribution.csv",sep=",",row.names=T, na = "NA")
write.csv(nmf_res$signature,file="/home/b06901011/mskcc-vcf2maf-bbe39fe/VCFMAF/sample_data/pic/nmf_res_signature.csv",sep=",",row.names=T, na = "NA")
write.csv(cos_sim_matrix(nmf_res$signatures,cancer_signatures),file="/home/b06901011/mskcc-vcf2maf-bbe39fe/VCFMAF/sample_data/pic/S2S_matrix.csv",sep=",",row.names=T, na = "NA")
